/**
 * Generating a design token stylesheet from the brand kit.
 *
 * The point is that it is generated. A tokens file written by hand is correct
 * on the day it is written and drifts from that moment on, and the drift is
 * silent: the colors in the kit and the colors in the file disagree, both look
 * plausible, and nobody finds out until two deliverables do not match.
 *
 * Colette already has a hand-written one and it has already drifted. Its
 * --second is #BCCFBB where the kit says #B2C9B3, and it omits Roundo
 * entirely, which is the face the wordmark is actually set in.
 *
 * WHAT THIS DOES NOT DO
 *
 * It emits variables and nothing else. No base rules, no components, no
 * layout. Those are decisions about one website and they belong to that
 * website's own stylesheet, where somebody can change them without editing
 * something called "the brand tokens". The hand-written file mixes both, which
 * is why it has to be maintained by hand.
 */

interface Color { name: string; hex: string; role?: string; token?: string }
interface Font {
  family: string;
  role?: string;
  weight?: string;
  tracking?: string;
  source?: string;
}

/** #RRGGBB to a WCAG relative luminance. */
function luminance(hex: string): number {
  const h = hex.replace('#', '');
  if (h.length !== 6) return 0;
  const parts = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
  const lin = parts.map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
  return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2];
}

export function contrast(a: string, b: string): number {
  const [x, y] = [luminance(a), luminance(b)].sort((p, q) => p - q);
  return Math.round(((y + 0.05) / (x + 0.05)) * 100) / 100;
}

/** A CSS custom property name, derived from the color's name if none is set. */
function tokenName(c: Color): string {
  if (c.token?.startsWith('--')) return c.token;
  return `--${c.name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
}

export function tokensCss(brandName: string, colors: Color[], fonts: Font[]): string {
  const lines: string[] = [];

  lines.push('/* ==========================================================================');
  lines.push(`   ${brandName} design tokens`);
  lines.push('');
  lines.push('   Generated from the brand kit. Do not edit this file by hand: it is');
  lines.push('   rewritten on every export, and a hand edit will be silently lost.');
  lines.push('   Change a color or a face in the kit and export again.');
  lines.push('');
  lines.push('   Variables only. Base rules, components and layout belong to the site');
  lines.push('   that uses these, not to the brand.');
  lines.push('   ========================================================================== */');
  lines.push('');
  lines.push(':root{');

  if (colors.length) {
    lines.push('');
    lines.push('  /* --- color ---------------------------------------------------------- */');
    const width = Math.max(...colors.map((c) => tokenName(c).length));
    for (const c of colors) {
      const name = tokenName(c).padEnd(width);
      const role = c.role ? `  /* ${c.name}. ${c.role} */` : `  /* ${c.name} */`;
      lines.push(`  ${name}: ${c.hex};${role}`);
    }
  }

  if (fonts.length) {
    lines.push('');
    lines.push('  /* --- type ----------------------------------------------------------- */');
    /**
     * A wordmark is not a display face.
     *
     * Colette has both, and mapping them to one variable made the wordmark
     * silently overwrite the headline face: two valid declarations, last one
     * wins, and the site renders every heading in the logo font. Nothing
     * errors, which is what makes it expensive to find.
     */
    const used = new Set<string>();
    for (const f of fonts) {
      const role = (f.role ?? '').toLowerCase();
      let key = /wordmark|logo/.test(role)
        ? '--f-wordmark'
        : /display|headline/.test(role)
        ? '--f-display'
        : /label|eyebrow/.test(role)
        ? '--f-label'
        : /body|ui/.test(role)
        ? '--f-body'
        : `--f-${f.family.toLowerCase().replace(/\s+/g, '-')}`;

      // Last defence against a collision the roles did not anticipate. Falling
      // back to the family name keeps both declarations rather than losing one.
      if (used.has(key)) key = `--f-${f.family.toLowerCase().replace(/\s+/g, '-')}`;
      used.add(key);

      /**
       * A real fallback on every stack.
       *
       * A hosted face that fails to load falls back to whatever the browser
       * picks, which on a wordmark is worse than not rendering at all. Serif
       * for display faces, sans for everything else, because a serif silently
       * replaced by Arial is the failure people actually notice.
       */
      const fallback = /display|headline|wordmark|logo/.test(role)
        ? "Georgia, 'Times New Roman', serif"
        : '-apple-system, BlinkMacSystemFont, system-ui, sans-serif';

      const note = [f.role, f.weight && `weight ${f.weight}`, f.tracking && `tracking ${f.tracking}`, f.source]
        .filter(Boolean)
        .join('. ');

      lines.push(`  ${key}: '${f.family}', ${fallback};${note ? `  /* ${note} */` : ''}`);
    }
  }

  lines.push('}');
  lines.push('');

  /**
   * Contrast, stated rather than assumed.
   *
   * The hand-written Colette file records none, and three of its pairings turn
   * out to be under the 4.5:1 floor for body text, including a focus ring that
   * sits at 1.16:1 on the dark grounds and is therefore invisible to anybody
   * navigating by keyboard. Nobody was careless; nothing was measuring.
   */
  const lights = colors.filter((c) => luminance(c.hex) > 0.4);
  const darks = colors.filter((c) => luminance(c.hex) <= 0.4);

  if (lights.length && darks.length) {
    lines.push('/* --- measured contrast --------------------------------------------------');
    lines.push('   Every dark on every light, computed at export. 4.5:1 is the floor for');
    lines.push('   body text and 3:1 for text above roughly 24px. Anything marked below');
    lines.push('   the floor is safe for large display type only.');
    lines.push('');
    for (const l of lights) {
      for (const d of darks) {
        const r = contrast(d.hex, l.hex);
        const verdict = r >= 4.5 ? 'body text' : r >= 3 ? 'large text only' : 'decorative only';
        lines.push(`   ${d.name} on ${l.name}: ${r.toFixed(2)}:1  ${verdict}`);
      }
    }
    lines.push('   -------------------------------------------------------------------- */');
    lines.push('');
  }

  return lines.join('\n');
}
